### ISSUE TITLE
IF just use ICH

### ISSUE THREAD

**Issue by qiezikuangge** [Yunfan-Li/Contrastive-Clustering#1]
If only the ICH is used, the method is SIMCLR in fact？

**Comment by Yunfan-Li** [comment]
Yes, indeed.

**Comment by qiezikuangge** [comment]
Ok,I see,thanks.

**Comment by echobear313** [comment]
Hello, I conducted the corresponding ablation experiment on cifar10. I found that the performance is better when only ICH head is used, which got 70.42 NMI score on cifar10. However, base on the same setting(bs:512, lr:0.0006), Contrastive Clustering got only 65.42 NMI score. Can you explain the performance. Thank you.

**Comment by Yunfan-Li** [comment]
I think it is possible ICH+K-means performs comparably with CC. In the paper, we find the performance improvement brought by CCH is limited on CIFAR-10 as well (from 0.699 to 0.705 in NMI). But on other datasets like ImageNet-10, CCH increases the performance from 0.838 to 0.859 in NMI. Thus we think the effectiveness of both contrastive heads depends on datasets. The importance of CCH not only lies in performance improvement but also in achieving online clustering. When only ICH is used, other clustering algorithms like K-means are needed, which is impractical for large datasets.
In our experiments, we also find the performance of CC decrease when the batch-size is larger than 256. We guess it is due to the instability of the Adam optimizer under large batch size and the LARS optimizer (as used in SimCLR) might help. Or have you tried other random seeds? Because in our experiments we have not seen such a performance gap between ICH+K-means and CC. Please let me know if you have any further questions.
